/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.matheus.View;

import com.matheus.Exception.PDException;
import com.matheus.Exception.PIException;
import com.matheus.Exception.SIException;
import com.matheus.Model.ITwitter;
import com.matheus.Model.Perfil;
import com.matheus.Model.Tweet;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.Vector;

/**
 *
 * @author matheus
 */
public class jfPerfil extends javax.swing.JFrame {
    private ITwitter twitter;
    private String usuarioPerfil;
    private String usuario;
    private boolean isFollowing;

    private void updateData(){
        try {
            this.lbUsuario.setText("@"+usuarioPerfil);
            this.lbSeguidores.setText(twitter.numeroSeguidores(this.usuarioPerfil)+" Seguidores");
            this.lbSeguindo.setText(twitter.numeroSeguidos(this.usuarioPerfil)+" Seguindo");

            Vector<Perfil> seguidores = twitter.seguidores(usuarioPerfil);
            for(Perfil perfil : seguidores){
                if(perfil.getUsuario().equals(usuario)){
                    this.btnCadastrar.setText("Já segue");
                    this.btnCadastrar.setEnabled(false);

                    break;
                }
            }


            Vector<Tweet> timeline = twitter.tweets(usuarioPerfil);
            ((DefaultTableModel)this.tbTweets.getModel()).setRowCount(0);
            for(int i = timeline.size() - 1; i >= 0; i--){
                Tweet tweet = timeline.elementAt(i);
                ((DefaultTableModel)this.tbTweets.getModel()).addRow(new Object[] { tweet.getUsuario(), tweet.getMensagem()});
            }


        } catch (Exception e) {
            this.dispose();
        }
    }

    /**
     * Creates new form jfHome
     */
    public jfPerfil(String usuarioPerfil, String usuario, ITwitter twitter) {
        initComponents();
        this.setResizable(false);
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        this.setTitle("My Twitter - Perfil");

        this.usuarioPerfil = usuarioPerfil;
        this.usuario = usuario;
        this.twitter = twitter;

        updateData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbTweets = new javax.swing.JTable();
        lbSeguidores = new javax.swing.JLabel();
        lbUsuario = new javax.swing.JLabel();
        lbSeguindo = new javax.swing.JLabel();
        btnCadastrar = new javax.swing.JButton();

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        jPanel1.setBackground(new java.awt.Color(20, 23, 26));

        jPanel2.setBackground(new java.awt.Color(20, 23, 26));

        tbTweets.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {

                },
                new String [] {
                        "Usuário", "Tweet"
                }
        ) {
            Class[] types = new Class [] {
                    java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                    false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tbTweets);

        lbSeguidores.setForeground(new java.awt.Color(245, 248, 250));
        lbSeguidores.setText("0 Seguidores");
        lbSeguidores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbSeguidoresMouseClicked(evt);
            }
        });

        lbUsuario.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lbUsuario.setForeground(new java.awt.Color(245, 248, 250));
        lbUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbUsuario.setText("@usuario");

        lbSeguindo.setForeground(new java.awt.Color(245, 248, 250));
        lbSeguindo.setText("0 Seguindo");
        lbSeguindo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbSeguindoMouseClicked(evt);
            }
        });

        btnCadastrar.setBackground(new java.awt.Color(29, 161, 242));
        btnCadastrar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnCadastrar.setForeground(new java.awt.Color(245, 248, 250));
        btnCadastrar.setText("Seguir");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 827, Short.MAX_VALUE))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(40, 40, 40)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addComponent(lbUsuario)
                                                                .addGap(0, 0, Short.MAX_VALUE))
                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addComponent(lbSeguidores, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(lbSeguindo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addContainerGap(33, Short.MAX_VALUE)
                                .addComponent(lbUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lbSeguidores)
                                        .addComponent(lbSeguindo)
                                        .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(16, 16, 16)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {
        // TODO add your handling code here:
    }

    private void lbSeguindoMouseClicked(java.awt.event.MouseEvent evt) {
        try {
            new jfLista(twitter.seguidos(usuario));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void lbSeguidoresMouseClicked(java.awt.event.MouseEvent evt) {
        try {
            new jfLista(twitter.seguidores(usuario));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            this.twitter.seguir(usuario,usuarioPerfil);
        } catch (SIException e) {
            e.printStackTrace();
        } catch (PDException e) {
            e.printStackTrace();
        } catch (PIException e) {
            e.printStackTrace();
        } finally {
            updateData();
        }
    }



    // Variables declaration - do not modify
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lbSeguidores;
    private javax.swing.JLabel lbSeguindo;
    private javax.swing.JLabel lbUsuario;
    private javax.swing.JTable tbTweets;
    // End of variables declaration
}
